# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2950832f0753e71b27d2c684f6ec39c90c4a41697c5cb4555d74019d514d25125978202a32760f4853d3e961eabc9e5c51c752cf0f9542302b72fd58dca55f58

test:
  secret_key_base: 72c70a464e620251f62c2204f5b26f48c36b006457bfb9595939f8e65e6730d11a0078e7f7692e62efbec78bed36e941a9d03ad8689adf032e2bee28adf83c1f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
